version: '3'

services:
  h2:
    image: 'h2'
    container_name: 'java-h2'
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_DB=mydb'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080