CREATE TABLE plant
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    address          VARCHAR(255),
    create_date      date,
    date_add_in_base date,
    CONSTRAINT pk_plant PRIMARY KEY (id)
);

CREATE TABLE device
(
    id                   BIGINT NOT NULL,
    ui                   VARCHAR(255),
    local_date           date,
    device_name          VARCHAR(255),
    name_director_change VARCHAR(255),
    plant_id             BIGINT,
    CONSTRAINT pk_device PRIMARY KEY (id)
);

ALTER TABLE device
    ADD CONSTRAINT "FK_DEVICE_ON_PLANT.ID" FOREIGN KEY (plant_id) REFERENCES plant (id);

INSERT into plant VALUES (1,'Тульский','Тула','1990-11-11','2024-01-01');

INSERT into device VALUES (1,'2is992m','2024-01-30','device','Ivan',1);
